version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/demo
      - DISCORD_BOT_TOKEN=
      - SPRING_AI_OPENAI_API_KEY=
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
  
